name = "ent-dental-polyclinic"
compatibility_date = "2024-01-15"

[env.production]
name = "ent-dental-polyclinic"

[build]
command = "npm run build"
cwd = "."

[[build.environment]]
NODE_VERSION = "18"
